search 7.4 | upgrading search for 7.4 | LRDOCS-9736
lipusz/liferay-learn pull request #43
Opened 2021-11-05 15:54 UTC by rbohl

Hey Tibor, see how this looks. There are some comments directly made to you (with questions) in the text.
https://issues.liferay.com/browse/LRDOCS-9736

2021-11-05 16:17 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/connecting-to-elasticsearch.md
> +* Liferay 7.3+: Liferay Connector to Elasticsearch is included in Liferay 7.3 and 7.4. It's also available on [Liferay Marketplace](../../../system-administration/installing-and-managing-apps/getting
There is no ES7 connector on Marketplace for 7.3 and 7.4. Please, remove that part.

2021-11-05 16:19 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/installing-elasticsearch.md
> +   The Sidecar Elasticsearch server bundled with Liferay 7.3+ uses the Elasticsearch OSS distribution. Do not install the OSS version for production. To run Liferay securely with Elasticsearch, you m
Currently, that still stands (7.10.2). However, the next time we bump the client we most probably will need to switch to the non-OSS version of ES affecting Sidecar and this text will need to be updated.

2021-11-05 16:29 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading-elasticsearch/backing-up-elasticsearch.md
> +<!-- verify whether anything has changed--can you simply reindex now on 7.4? probably still needed because on 7.3 customers may have non-db-backed tuning data. also, when a customer upgrades to the n
It has changed, see the related stories.

Regarding the need for backing-up and restoring the tuning indexes: 
1. If you **upgrade your existing Elastic Stack** from 6.x to 7.x, or from anything 7.x to a compatible 7.x version: Backup: recommended, Restore: not needed, since your data has been upgraded, thus preserved in Elasticsearch.
2. If you **upgrade your DXP deployment** AND it is **connecting to the same Elasticsearch cluster** during the upgrade: Backup: recommended, Restore: not needed, since you are using the same cluster, the tuning indexes will be there.
3. If you **upgrade your DXP deployment** AND it is **not connecting to the same ES cluster**: Backup: recommended, **Restore: needed**. Plus, after restoring the indexes in ES, you must also run those 2 groovy-scripts from the related stories to load those tuning entries into the DB.

Performing a full reindex after finishing the DXP upgrade is always a must.

2021-11-05 16:30 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading-elasticsearch/upgrading-search-with-liferay.md
> +# Upgrading Search with Liferay
I'm thinking about a better title. :thinking: @lipusz TODO

2021-11-05 16:31 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading-elasticsearch/upgrading-search-with-liferay.md
> +* Liferay Enterprise Search is now bundled with Liferay DXP. No additional installation steps are required. See [Activating Liferay Enterprise Search](../../../liferay-enterprise-search/activating-li
I think the correct wording is _Liferay Enterprise Search **applications are now bundled**_ as "LES" is not a thing.

2021-11-05 16:32 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading-elasticsearch/upgrading-search-with-liferay.md
> +* Beginning in Liferay 7.4, the Search Tuning (Synonym Sets and Result Rankings) indexes are backed by database tables. If the search engine is connected to Liferay during upgrade, the data will be p
>you'll need to run a [Groovy script](#importing-the-search-tuning-indexes-in-74) to manually import the index data into the new database tables.

but **only if the tuning indexes have been restored from a snapshot previously!**

2021-11-05 16:34 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading-elasticsearch/upgrading-search-with-liferay.md
> +Provide the scenario and the usage for the groovy script.
See what I wrote earlier.

2021-11-05 16:37 UTC, lipusz requested changes
I think I covered everything, Let me know if I didn't. :-)

2021-11-05 21:00 UTC, rbohl commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/upgrading-elasticsearch/upgrading-search-with-liferay.md
> +# Upgrading Search with Liferay
How about one of these?
* _Upgrading Search Infrastructure_ 
* _Upgrading Liferay's Search Infrastructure_
* _Search Upgrade Overview_

2021-11-05 21:49 UTC, rbohl commented
Pushed up a new commit. Waddya think?

2021-11-06 14:20 UTC, lipusz commented on docs/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/elasticsearch/installing-elasticsearch.md
> +If you have Elasticsearch indexes used for primary data storage (storing data not backed by a database) you can bring that data into your new Elasticsearch cluster using the `snapshot and restore app
They are primary storage on 7.2 and 7.3.

2021-11-08 10:28 UTC, lipusz commented
https://github.com/rbohl/liferay-learn/pull/106

2021-11-08 10:28 UTC, closed without merging